#!/bin/sh

# Source: https://github.com/qmk/qmk_fpm

# Add the QMK source to your apt repositories list:
echo "deb https://linux.qmk.fm/ $(lsb_release --codename --short) main" | sudo tee /etc/apt/sources.list.d/qmk.list

# Add the QMK GPG Key:
wget -qO - https://linux.qmk.fm/gpg_pubkey.txt | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/qmk-gpg-pubkey.gpg > /dev/null

# Update apt:
sudo apt update

# Install QMK:
sudo apt install qmk

# Setuo QMK:
qmk setup
