#!/bin/sh

main() {
  if apt >/dev/null 2>&1; then
    echo "Only support Debian-based systems"
    exit 1
  fi

  # Source: https://github.com/qmk/qmk_fpm

  # Add the QMK source to your apt repositories list:
  CODENAME=$(lsb_release --codename --short)

  if [ "$CODENAME" = "trixie" ]; then
    CODENAME="bookworm"
  fi

  echo "deb https://linux.qmk.fm/ $CODENAME main" | sudo tee /etc/apt/sources.list.d/qmk.list

  # Add the QMK GPG Key:
  wget -qO - https://linux.qmk.fm/gpg_pubkey.txt | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/qmk-gpg-pubkey.gpg >/dev/null

  # Update apt:
  sudo apt update

  # Install QMK:
  sudo apt install qmk

  # Setuo QMK:
  qmk setup

  exit 0
}

main
